var apibse = "https://sultan-delivery-v1.herokuapp.com/api/";
var catapi = "cats/?format=json";
var foodapi = "foods/?format=json";
var specifyapi = "specifyz/?format=json";
var requestdetailapi = "request_details/?format=json";
var transformapi = "transports/?format=json";
var foodz = "foodz/?format=json";
var requestz = "requestz/?format=json";
var phoneid = '';
List<String> favorites = [];
var catlist;
